### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by sagikazarmark** [shykes/git#4]
Would you accept a PR adding some automated tests like these: https://github.com/sagikazarmark/daggerverse/tree/main/helm/tests?

**Comment by shykes** [comment]
Gladly, although I've been using the convention of a `dev/` submodule, if you don't mind using that name? I like it because it allows for adding more than just tests. For example I started pinning all my external data sources (images, git repos), and I use functions in `dev` to fetch the latest digests.

**Comment by sagikazarmark** [comment]
Sounds good to me
